services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_container
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER:-root}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_USER:-root}
    volumes:
      - mongodb:/data/db
    networks:
      - practia-1
  backend:
    build:
      context: ./practica_1
      dockerfile: dockerfile
    container_name: my-backend-container_name
    restart: always
    env_file:
      - ./.env
    ports:
      - "3000:3000"
    networks:
      - practia-1
    depends_on:
      - mongodb
networks:
  practia-1:
    driver: bridge
volumes:
  mongodb: {}