version: "3.8"

services:
  #Servicio de mongo 
  mongo:
    #Necesito decirle donde esta la imagen
    #el volumen y la red
    image: mongo:6.0
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER:-root}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_USER:-root}
      - MONGO_INITDB_DATABASE:${MONGO_DB:-university}
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network
    
  api:
    build: .
    restart: unless-stopped
    depends_on:
      - mongo
    ports:
     - "3000:3000"
    environment:
      MONGO_USER: ${MONGO_USER:-root}
      MONGO_PASS: ${MONGO_PASS:-root}
      MONGO_HOST: mongo
      MONGO_PORT: 27017
      MONGO_DB: ${MONGO_DB:-university}

    networks:
      - app-network
volumes:
  mongo-data: {}
networks:
  app-network:
    driver: bridge