FROM node:24-alpine     
#Desde imagen de node
WORKDIR /usr/src/app    # Carpeta de trabajo
#Copiar dependencias a la raiz
COPY package*.json ./   
#Ejectuar la instalacion de depencias
RUN npm ci --only=production
# Copiar el resto
COPY . .
#Exponer el puerto
EXPOSE 3000
#Comando de arranque
CMD [ "node","index.js" ]